name: test-docker
on:
  push:
    branches:
      - docker/**

jobs:
  buildPush:
    runs-on: ubuntu-latest
    if: github.event.repository.fork
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ vars.NODE_VERSION_OVERRIDE || 'lts/*' }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: salesforce/cli

      - name: Collect Node checksum
        id: node-checksum
        run: |
          NODE_VERSION="$STEPS_SETUP_NODE_NODE_VERSION"

          URL="https://nodejs.org/dist/$NODE_VERSION/SHASUMS256.txt"
          echo "Retrieving SHA data from: $URL"

          SHA=$(curl -s "$URL" | awk "/[0-9a-f]{64}  node-$NODE_VERSION-linux-x64.tar.gz/ { print \$1 }")
          echo "Checksum found: $SHA"

          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
        env:
          STEPS_SETUP_NODE_NODE_VERSION: ${{ steps.setup-node.outputs.node-version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile
          build-args: |
            NODE_VERSION=${{ steps.setup-node.outputs.node-version }}
            NODE_CHECKSUM=${{ steps.node-checksum.outputs.sha }}
            SF_CLI_VERSION=${{ inputs.version || 'latest' }}
          tags: salesforce/cli:${{ inputs.channel }}-full, salesforce/cli:${{ inputs.version || 'latest' }}-full

  verify:
    needs: buildPush
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:${{ inputs.version || 'latest' }}-full
    steps:
      - name: verify node, sf, jq
        # without bash this will fail.  Not sure what the default shell is but it doesn't like the [[(())]] bashism
        shell: bash
        run: |
          set -e
          node -v
          sf version --verbose
          jq --help
          NODE_VERSION=$(sf version --verbose --json | jq '.nodeVersion')
          SF_CLI_VERSION=$(sf version --verbose --json | jq '.cliVersion')
          if [[ ((`echo $SF_CLI_VERSION | grep -c "@salesforce/cli/"` > 0))]]
          then
            echo "sf installed -" $SF_CLI_VERSION
          else
            echo "The sf installation could not be verified"
            exit 1
          fi
          if [[ ((`echo $NODE_VERSION | grep -c "v"` > 0))]]
          then
            echo "node installed -" $NODE_VERSION
          else
            echo "The node installation could not be verified"
            exit 1
          fi
